---
- name: check if atomic host
  stat:
    path: /run/ostree-booted
  register: ostree

- set_fact:
    is_atomic: "{{ ostree.stat.exists }}"

- set_fact:
    kube_cert_group: "kube"
  when: is_atomic

- include: set_resolv_facts.yml
  tags:
    - bootstrap-os
    - resolvconf
    - facts

- name: check if fedora host
  register: fedora
  command: grep "NAME=Fedora" /etc/os-release
  check_mode: no
  ignore_errors: yes
  changed_when: no

- set_fact:
    is_fedora: "{{ fedora.rc }} == 0"
